[package]
name = "tsc-solution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
etherparse = "0.13.0"
pcap-file = "2.0.0"
